included:
  - Application
  - Common
  - Extensions
  - TV Application
  - UITests

disabled_rules:
  - cyclomatic_complexity
  - identifier_name
  - force_cast
  - force_try
  - function_body_length
  - multiple_closures_with_trailing_closure
  - statement_position
  - todo
  - type_body_length

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - duplicate_conditions
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - sorted_first_last
  - static_operator
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  
analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

line_length: 300
file_length: 1000

trailing_whitespace:
  ignores_empty_lines: true
  severity: warning

type_name:
  excluded:
    - Id

function_parameter_count:
  warning: 8

nesting:
  type_level: 2