//
//  Copyright (c) SRG SSR. All rights reserved.
//
//  License information is available from the LICENSE file.
//

#import "HomeSection.h"

NS_ASSUME_NONNULL_BEGIN

/**
 *  @name Analytics standard page levels
 */
typedef NSString * AnalyticsPageLevel NS_STRING_ENUM;

OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelApplication;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelAudio;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelAutomobile;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelEpisode;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelFeature;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelGoogleCast;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelLive;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelMostPopular;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelPlay;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelPreview;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelScheduledLivestream;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelSearch;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelSection;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelShow;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelSignLanguage;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelTopic;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelUser;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelVideo;

/**
 *  @name Analytics standard page titles
 */
typedef NSString * AnalyticsPageTitle NS_STRING_ENUM;

OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleDevices;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleDownloads;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleFavorites;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleFeatures;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleHistory;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleHome;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLatest;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLatestEpisodes;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLatestEpisodesFromFavorites;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLicense;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLicenses;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLivePrograms;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLogin;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleMedia;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleMostPopular;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleNotifications;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitlePlayer;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleProgramGuide;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleRadio;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleRadioSatellite;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleResumePlayback;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleScheduledLivestreams;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleSettings;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleHelpAndContact;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleShowsAZ;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleShowsCalendar;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleSports;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleTopics;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleTV;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleWatchLater;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleWhatsNew;

NS_ASSUME_NONNULL_END
