//
//  Copyright (c) SRG SSR. All rights reserved.
//
//  License information is available from the LICENSE file.
//

#import "HomeSection.h"

NS_ASSUME_NONNULL_BEGIN

/**
 *  @name Analytics standard page levels
 */
typedef NSString * AnalyticsPageLevel NS_STRING_ENUM;

OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelApplication;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelAudio;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelAutomobile;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelEpisode;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelFeature;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelGoogleCast;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelLive;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelMostPopular;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelPlay;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelPreview;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelScheduledLivestream;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelSearch;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelSection;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelShow;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelSignLanguage;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelTopic;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelUser;
OBJC_EXPORT AnalyticsPageLevel const AnalyticsPageLevelVideo;

/**
 *  @name Analytics standard page titles
 */
typedef NSString * AnalyticsPageTitle NS_STRING_ENUM;

OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleDevices;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleDownloads;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleFavorites;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleFeatures;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleHistory;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleHome;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLatest;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLatestEpisodes;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLatestEpisodesFromFavorites;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLicense;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLicenses;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLivePrograms;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleLogin;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleMedia;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleMostPopular;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleNotifications;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitlePlayer;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleProgramGuide;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleRadio;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleRadioSatellite;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleResumePlayback;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleScheduledLivestreams;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleSettings;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleShowsAZ;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleShowsCalendar;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleSports;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleTopics;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleTV;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleWatchLater;
OBJC_EXPORT AnalyticsPageTitle const AnalyticsPageTitleWhatsNew;

/**
 *  @name Analytics event values
 */
typedef NSString * AnalyticsSource NS_STRING_ENUM;
typedef NSString * AnalyticsType NS_STRING_ENUM;

/**
 *  Sources
 */
OBJC_EXPORT AnalyticsSource const AnalyticsSourceAutomatic;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceButton;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceClose;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceContextMenu;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceCustomURL;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceNotification NS_SWIFT_NAME(AnalyticsSource.notification);
OBJC_EXPORT AnalyticsSource const AnalyticsSourceNotificationPush;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceSelection;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceSwipe;
OBJC_EXPORT AnalyticsSource const AnalyticsSourceUniversalLink;

/**
 *  Actions
 */
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionFavorites;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionDownloads;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionHistory;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionSearch;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionPlayMedia;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionDisplay;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionDisplayShow;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionDisplayPage;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionDisplayURL;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionCancel;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionNotificationAlert;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionDisplayLogin;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionCancelLogin;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionLogin;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionLogout;
OBJC_EXPORT AnalyticsType const AnalyticsTypeActionOpenPlayApp;

NS_ASSUME_NONNULL_END
