//
//  Copyright (c) SRG SSR. All rights reserved.
//
//  License information is available from the LICENSE file.
//

// This file lists all Objective-C headers which must be exposed to Swift code. Update the list as needed. All referenced
// Objective-C headers will be automatically exposed to all Swift source files.

#import "ApplicationConfiguration.h"
#import "ApplicationSettings.h"
#import "ApplicationSettings+Common.h"
#import "ApplicationSettingsConstants.h"
#import "Banner.h"
#import "BaseViewController.h"
#import "CalendarViewController.h"
#import "ChannelService.h"
#import "Download.h"
#import "Favorites.h"
#import "GoogleCastBarButtonItem.h"
#import "History.h"
#import "Layout.h"
#import "MediaPlayerViewController.h"
#import "MediaPlayerViewController+Private.h"
#import "MediaPreviewViewController.h"
#import "NavigationController.h"
#import "NSBundle+PlaySRG.h"
#import "NSDateFormatter+PlaySRG.h"
#import "Onboarding.h"
#import "PlayAccessibilityFormatter.h"
#import "PlayApplicationNavigation.h"
#import "PlayDurationFormatter.h"
#import "PlayErrors.h"
#import "PushService.h"
#import "Reachability.h"
#import "RefreshControl.h"
#import "SceneDelegate.h"
#import "SearchSettingsViewController.h"
#import "SharingItem.h"
#import "SongsViewController.h"
#import "SRGChannel+PlaySRG.h"
#import "SRGLetterboxController+PlaySRG.h"
#import "SRGMedia+PlaySRG.h"
#import "SRGProgram+PlaySRG.h"
#import "SRGProgramComposition+PlaySRG.h"
#import "UIColor+PlaySRG.h"
#import "UICollectionView+PlaySRG.h"
#import "UIDevice+PlaySRG.h"
#import "UIImage+PlaySRG.h"
#import "UIImageView+PlaySRG.h"
#import "UIScrollView+PlaySRG.h"
#import "UIViewController+PlaySRG.h"
#import "UIWindow+PlaySRG.h"
#import "WatchLater.h"
