#!/bin/sh

#================================================================
# Append Jira issue key into commit message
#================================================================

# Inspired from: https://community.atlassian.com/t5/Bitbucket-questions/automatically-append-JIRA-issue-ID-into-commit-message/qaq-p/605991

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Search jira issue key from the branch name in a pattern such a "feature/ABC-123-description"
JIRA_ISSUE_KEY=$(echo "$BRANCH_NAME" | sed -nr 's,[a-z]+/([A-Z0-9]+-[0-9]+)-.+,\1,p')

# A developer may have already prepended the commit message with the branch jira issue key
JIRA_ISSUE_KEY_IN_COMMIT=$(grep -c "$JIRA_ISSUE_KEY" "$1")

# Only amend commit message if jira issue key was found and not already in commit message
if [ -n "$JIRA_ISSUE_KEY" ]  && ! [ "$JIRA_ISSUE_KEY_IN_COMMIT" -ge 1 ]; then
 echo "📝 Prepending jira issue $JIRA_ISSUE_KEY to commit message"
 sed -i.bak -e "1s/^/$JIRA_ISSUE_KEY /" "$1"
fi