#!/bin/sh

#================================================================
# Quality check
#================================================================

eval "$(rbenv init -)"
PATH="$(which swiftlint):$(which swiftformat):$(which ruby):$(which shellcheck):$(which yamllint):$(which pod):$PATH"

if Scripts/check-quality.sh only-changes; then
	echo "✅ Quality checked"
else
	echo "❌ Quality check failed"
	exit 1
fi
