# frozen_string_literal: true

# A list of devices you want to take the screenshots from
devices([
          'iPhone 11', # 6.5 inch, required
          'iPhone 8 Plus', # 5.5 inch, required
          'iPad Pro (12.9-inch) (3rd generation)', # 12.9 inch, required
          'iPad Pro (12.9-inch) (2nd generation)' # 12.9 inch, required
        ])

configuration('AppStore')

clear_previous_screenshots(true)

localize_simulator(true)
reinstall_app(true)
