# frozen_string_literal: true

# A list of devices you want to take the screenshots from
devices([
          'iPhone 11 Pro Max', # 6.5 inch, required
          'iPhone 8 Plus', # 5.5 inch, required
          'iPad Pro (12.9-inch) (4th generation)', # 12.9 inch, required
          'iPad Pro (12.9-inch) (2nd generation)' # 12.9 inch, required
        ])

configuration('AppStore')
clean(true)

clear_previous_screenshots(true)

localize_simulator(true)
reinstall_app(true)

launch_arguments(['SKIP_TV_EVENTS'])
