# frozen_string_literal: true

configuration('AppStore')
xcargs('ONLY_ACTIVE_ARCH=YES')

clear_previous_screenshots(true)

localize_simulator(true)
override_status_bar(true)
reinstall_app(true)

headless(true)
number_of_retries(0)

launch_arguments(['SKIP_TV_EVENTS'])
